## Aula 2 - Numpy

Nessa aula, iremos tratar dos seguintes conteúdos:

- NumPy
- Arrays
- Operações Matemáticas
- Alguns Métodos NumPy
- Indexação
- Máscara Booleana
- Bonus: List Comprehension

## NumPy

 A biblioteca __NumPy__ (_Numerical Python_) é um pacote do Python para a __armazenagem__ e __processamento__ de conjuntos de dados na forma __matricial__ (computação orientada por matrizes).
 
 Outras bibliotecas com o __Pandas__, __MatplotLib__ e __Scikit Learn__ dependem fortemente do __Numpy__, devido a sua eficiência computacional, sendo amplamente utilizado para __computação científica__ e __análise de dados.__
 
 O __NumPy__ é um pacote e para utilizarmos, devemos importá-lo para o nosso notebook da seguinte forma:

In [1]:
import numpy as np

## Arrays

A estrutura de dados base do __NumPy__ são os `arrays`, que funcionam de forma parecida com as listas em Python, vamos comparar semelhanças e diferenças

Diferenças:
- Todos os elementos em um array deve ser do mesmo tipo, tipicamente um tipo numérico como __float__ ou __int__
- Os arrays viabilizam a realização eficiente de operações numéricas envolvendo grandes quantidades de dados, sendo para este fim, muito mais eficientes que as listas.
- Cada dimensão de um array é chamada de eixo (_axis_)

Semelhanças:
- Os eixos são numerados a partir de $0$
- Os elementos são acessados utilizando colchetes __[]__ (semelhante às listas do Python)

#### Conversão de Listas para Arrays

Pra criar arrays a partir de uma lista, basta utilizar o procedimento **np.array():**

In [2]:
## Definir uma lista
lista=[1,2,3,4,5,6]

## Fazendo a conversão
array = np.array(lista)

In [3]:
## Print comparativo
print(lista)
print(array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


## Operações Matemáticas entre arrays

In [4]:
## Contas com constantes

In [5]:
## Contas entre arrays

## Exercício

Vamos fazer um exercício para dar uma revisada nos conhecimentos de python e ao mesmo tempo praticar o que aprendemos até aqui. Construa um programa onde o usuário digita uma lista de preços de produtos. Depois peça ao lojista que digite uma lista de descontos em percentagem.

De posse das duas listas, transforme ambas em Arrays NumPy e calcule a lista dos preços resultantes desta compra!

In [6]:
lista_1 =[]
lista_2 = []

for item in range(5):
    lista_1.append(float(input('Digite o valor do produto ' + str(item+1) + ':')))
array_1 = np.array(lista_1)
print(lista_1)
print(array_1)

Digite o valor do produto 1:100
Digite o valor do produto 2:200
Digite o valor do produto 3:300
Digite o valor do produto 4:400
Digite o valor do produto 5:500
[100.0, 200.0, 300.0, 400.0, 500.0]
[100. 200. 300. 400. 500.]


In [7]:
for item in range(5):
    lista_2.append(float(input('Digite o valor do desconto' + str(item+1) + ':')))
array_2 = np.array(lista_2)
print(lista_2)
print(array_2)

Digite o valor do desconto1:10
Digite o valor do desconto2:25
Digite o valor do desconto3:35
Digite o valor do desconto4:45
Digite o valor do desconto5:50
[10.0, 25.0, 35.0, 45.0, 50.0]
[10. 25. 35. 45. 50.]


In [8]:
array = array_1 * (1 - (array_2/100))
print(array)

[ 90. 150. 195. 220. 250.]


## Alguns métodos do NumPy para criar Arrays

Outra forma de criarmos arrays seria usando __métodos NumPy__ como por exemplo __np.zeros__, __np.ones__ e outros mais:

In [9]:
## Array de Zeros
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
## Array de Uns
arr_ones = np.ones(10)

print(arr_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
## Revisão método range
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [17]:
## Array de Range
arr_sequencia = np.arange(10)
arr_range = np.arange(11, 21)
arr_pares = np.arange(0, 100, 2)

print(arr_sequencia)
print(arr_range)
print(arr_pares)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [18]:
## linspace -> Fatiamento de intervalo
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [19]:
## Distribuição aleatória entre 0 e 1
arr_random = np.random.rand(10)
print(arr_random)

[0.92456113 0.77065799 0.54682129 0.6669564  0.98237416 0.35139218
 0.33431728 0.30117147 0.73060319 0.98383503]


In [33]:
## Distribuição aleatoria e normal
arr_normal = np.random.normal(1, 0, 10)
print(arr_normal)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
## distribuição aleatória e inteira
arr_inteiros = np.random.randint(0, 100, 20)
print(arr_inteiros)

[11 94 34 58 69 74 82 70 55 21 94  8 75  3 25 75 43  3 73  4]


## Métodos do NumPy para estatística e ordenação

In [25]:
## Método sort
arr_inteiros.sort()
print(arr_inteiros)

[ 0  0 21 33 35 41 48 50 53 54 61 64 70 71 74 77 77 80 83 89]


In [28]:
## Método argsort
indice = np.argsort(arr_inteiros)
print(arr_inteiros)
print(indice)

[11 94 34 58 69 74 82 70 55 21 94  8 75  3 25 75 43  3 73  4]
[17 13 19 11  0  9 14  2 16  8  3  4  7 18  5 12 15  6 10  1]


In [29]:
## Método max
arr_inteiros.max()

94

In [30]:
## Método min
arr_inteiros.min()

3

In [31]:
## Metodo sum
arr_inteiros.sum()

971

In [34]:
## Metodo mean
lista_simples = [1, 2, 3,]
arr_normal.mean()

1.0

In [35]:
## Metodo std
arr_inteiros.std()

31.344018568141514

In [39]:
## Metodo argmax
print(arr_inteiros)
arr_inteiros.argmax()

[11 94 34 58 69 74 82 70 55 21 94  8 75  3 25 75 43  3 73  4]


1

In [40]:
## Metodo argmin
print(arr_inteiros)
arr_inteiros.argmin()

[11 94 34 58 69 74 82 70 55 21 94  8 75  3 25 75 43  3 73  4]


13

## Exercício

Mais um exercício onde queremos um pouco de revisão. Faça um programa que gera aleatóriamente as notas de 20 alunos entre 0 e 10 (notas quebradas são permitidas, um 8.4 por exemplo é uma nota válida). Em seguida, calcule a média dessa turma

In [70]:
arr_notas = np.round_(np.random.uniform(0, 10, 20), decimals = 1)
print(arr_notas)

print('media dos 20 alunos é: ' + str(arr_notas.mean()))

[8.9 4.3 8.6 4.5 0.3 0.9 5.3 4.6 9.8 7.5 3.2 0.8 9.1 9.6 6.3 0.8 2.3 3.5
 3.1 2.4]
media dos 20 alunos é: 4.79


## Indexação

In [77]:
## Acesso a elemento
array = np.arange(7, 20, 1)
print(array)
print(array[1])
print(array[-2])

[ 7  8  9 10 11 12 13 14 15 16 17 18 19]
8
18


In [82]:
## Array Slicing
print(array[1:5])

print(array[:3])

print(array[3:])

print(array[::])

[ 8  9 10 11]
[7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[ 7  8  9 10 11 12 13 14 15 16 17 18 19]


## Mascára Booleana

In [83]:
## Construindo uma máscara
array = np.arange(20)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [92]:
## Como a máscara se parece?
mascara = array > 7
print(mascara)
m = array%2
print(m)

[False False False False False False False False  True  True  True  True
  True  True  True  True  True  True  True  True]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [94]:
## Acessando o array com a mascara
print(array[mascara])
print(array[m])

[ 8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [90]:
## Máscara composta
mascara_composta = (array > 10) & (array < 15)
print(array[mascara_composta])

[11 12 13 14]


## Exercícios

1 - Faça uma máscara que identifique num array se os elementos são pares ou não

2 - Volte no exercício da lista de notas. Se a media for 7, quais deles terão passado? Use uma mascara para descobrir

3 - Quais foram acima da média?

In [97]:
array = np.arange(20)
m = array%2 == 0
print(m)
print(array[m])

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
[ 0  2  4  6  8 10 12 14 16 18]


In [107]:
arr_notas = np.round_(np.random.uniform(0, 10, 20), decimals = 1)
print('notas da turma', arr_notas)

m = arr_notas >= 7
print('Alunos aprovados', arr_notas[m])

m2 = (arr_notas > arr_notas.mean()) & (arr_notas < 7)
m3 = arr_notas < arr_notas.mean()
print('Alunos com chance de recuperação', arr_notas[m2])

print('Alunos reprovados', arr_notas[m3])

print('media dos 20 alunos é: ' + str(arr_notas.mean()))

notas da turma [5.9 9.6 9.3 1.9 1.7 2.4 7.3 3.3 7.8 0.9 6.3 1.3 6.2 2.2 3.6 1.8 6.5 5.9
 9.7 5.5]
Alunos aprovados [9.6 9.3 7.3 7.8 9.7]
Alunos com chance de recuperação [5.9 6.3 6.2 6.5 5.9 5.5]
Alunos reprovados [1.9 1.7 2.4 3.3 0.9 1.3 2.2 3.6 1.8]
media dos 20 alunos é: 4.955


## List Comprehension

<img src='https://miro.medium.com/max/858/0*ChFR2D9j8fxqz3D5.png' width=800>

## Exercício - Desafio

Utilize comprehension para gerar a lista de todos os números pares entre 0 e 19. Converta a lista em um __numpy__ array e cálcule a média.

In [108]:
even_squares = []
for num in range(11):
    if num%2 == 0:
        even_squares.append(num*num)

In [109]:
print(even_squares)

[0, 4, 16, 36, 64, 100]


In [110]:
even = []
for num in range(20):
    if num%2 == 0:
        even.append(num)

In [111]:
print(even)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [112]:
arr_even = np.array(even)
print(arr_even)

[ 0  2  4  6  8 10 12 14 16 18]


In [114]:
print(arr_even.mean())

9.0
